### ISSUE TITLE
composer config-build breaks autoloading

### ISSUE THREAD

**Issue by graste** [honeybee/honeybee-agavi-cmf-vendor#1] opened 2015-09-07 12:42 UTC
After running ```composer config-build``` I can't run `composer test` successfully as the autoloading doesn't work then. This autoloading error seems to happen always after running ```config-build```. I suspect the ```ConfigurationHandler::makeAutoload()``` method might be the problem, but didn't investigate further.

**Comment by MrHash** [comment] 2015-09-07 12:59
I think I came across a [bug](https://github.com/honeybee/honeybee-agavi-cmf-vendor/commit/80bf378e381c56b57d73e70b9b1023cd623dc112) previously which had a similar problem. Could you check that this is not the cause?

**Comment by graste** [comment] 2015-09-07 19:27
Will have a look, but I think my dependencies were up-to-date.

**Comment by graste** [comment] 2015-09-08 13:49
MrHash suggested to change the `ConfigurationHandler` method to https://gist.github.com/MrHash/c82f11e51d51bb34cf45 – seems to work in my working copy as it fixes the problem.

**Comment by MrHash** [comment] 2015-09-08 14:41
Fixed in 5a5f65725a3c870daadc9e48b8812ab57f2ebc02

**Closed by MrHash** 2015-09-08 14:41 UTC
Labels: bug
